//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalManagementySite
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalInventory
    {
        public int MedicalInventoryId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string SupplierName { get; set; }
        public string SupplierPhone { get; set; }
    }
}
